### ISSUE TITLE
Selenoid devtool APIS hang when run testcases parallely

### ISSUE THREAD

**Issue by Manikandan-Zoho** [aerokube/chrome-developer-tools-protocol-java-example#2]
I'm using selenoid 1.10.0 Linux binary
Usinf chrome browser v81.0
docker image - selenoid/vnc_chrome:81.0
OS - Ubuntu - 18.04
Using cdt-java-client-2.1.0.jar file

I have run more than 500 test cases parallelly running with 20 to 50 browser, I'm taking a screenshot and navigate a page using selenoid devtool, if I run the single case or run the test cases parallelly below 10 browsers it working fine.

If I run the test cases parallelly using more than 10 browsers, below exception occurs some test case steps

1. Chrome devtool service creation API got hang
2. Page.captureScreenshot(); method got hang
3. page.navigate(url); method got hang

that's why my test case is hanging infinitely

**Note:**

- I have run test case parallelly 20 browsers or more
- Single test case having a minimum of 20 steps every step I have to create a new devtool connection and take a screenshot

Is creating a devtool connection for every step is correct?

`
In my code

public class DevTools {
		
	public static ChromeDevToolsService connect(WebDriver driver, String driverIp) {
		 try {
			 // Init ChromeDevtools client
			 URL url = new URL(driverIp);
			 String webSocketUrl = String.format("ws://" + url.getHost() + ":" + url.getPort() + "/devtools/%s/page", SeCustomActions.getSessionId(driver));
			 WebSocketService webSocketService = WebSocketServiceImpl.create(new URI(webSocketUrl));
			 CommandInvocationHandler commandInvocationHandler = new CommandInvocationHandler();
			 Map<Method, Object> commandsCache = new ConcurrentHashMap<>();
			 ChromeDevToolsServiceConfiguration devtoolConf = new ChromeDevToolsServiceConfiguration();
			 devtoolConf.setReadTimeout(300);
			 ChromeDevToolsService devtools =
					 ProxyUtils.createProxyFromAbstract(
							 ChromeDevToolsServiceImpl.class,
							 new Class[] {WebSocketService.class, ChromeDevToolsServiceConfiguration.class},
							 new Object[] {webSocketService, devtoolConf},
							 (unused, method, args) ->	
							 commandsCache.computeIfAbsent(
									 method,
									 key -> {
										 Class<?> returnType = method.getReturnType();
										 return ProxyUtils.createProxy(returnType, commandInvocationHandler);
									 }));
			 commandInvocationHandler.setChromeDevToolsService(devtools);
			 return devtools;
		 }
		 catch(Exception e) {
			 e.printStackTrace();
		 }
		 return null;
	}

	public static void closeDevTool(ChromeDevToolsService devtool) {
		try {
			devtool.close();
		}
		catch(Exception e) {
			e.printStackTrace();
		}
	}
	
    public static String takeScreenshot(WebDriver driver, String driverIp) throws Exception {
    	ChromeDevToolsService devtool = connect(driver, driverIp);
    	Page page = devtool.getPage();
        String encodedScreenshot = page.captureScreenshot();
        encodedScreenshot = "data:image/png;base64," + encodedScreenshot;
		closeDevTool(devtool);
		return encodedScreenshot;
    }
    
    public static Navigate navigate(WebDriver driver, String driverIp, String url) throws Exception {
    	ChromeDevToolsService devtool = connect(driver, driverIp);
    	Page page = devtool.getPage();
    	Navigate navigate = page.navigate(url);
    	closeDevTool(devtool);
    	return navigate;
    }
    
    public static void reload(WebDriver driver, String driverIp) throws Exception {
    	ChromeDevToolsService devtool = connect(driver, driverIp);
    	Page page = devtool.getPage();
    	page.reload();
    	closeDevTool(devtool);
    }

}
`

Kindly check and give the solution for that
Thanks in advance

**Comment by vania-pooh** [comment]
@Manikandan-Zoho Selenoid is just reverse-proxying websocket traffic, so could be Chrome issue.

**Comment by Manikandan-Zoho** [comment]
@vania-pooh Now, I create devtool connections for every single step.
Is this fine creating a single connection for a tab?
Is there any problem with creating frequent devtool connections for every single step?
Creating a parallel connection makes any problem with that?
Please help me to solve this

**Comment by vania-pooh** [comment]
@Manikandan-18 I would expect to do one connection per Selenium session.

**Comment by Manikandan-18** [comment]
@vania-pooh Now I'm using one connection per tab, devtool connection creation working fine, but the below exception occurred sometimes.

page.captureScreenshot();
profiler.takePreciseCoverage();

timeout expired exception occurred, I think I was set the read timeout in chrome devtool service configuration due to the exception occur, before I set the read timeout the API hanged infinity. Please help me to solve this

com.github.kklisura.cdt.services.exceptions.ChromeDevToolsInvocationException: Timeout expired while waiting for server response.
	at com.github.kklisura.cdt.services.impl.ChromeDevToolsServiceImpl.invoke(ChromeDevToolsServiceImpl.java:149)
	at com.github.kklisura.cdt.services.invocation.CommandInvocationHandler.invoke(CommandInvocationHandler.java:87)
	at com.sun.proxy.$Proxy22.takePreciseCoverage(Unknown Source)

com.github.kklisura.cdt.services.exceptions.ChromeDevToolsInvocationException: Timeout expired while waiting for server response.
	at com.github.kklisura.cdt.services.impl.ChromeDevToolsServiceImpl.invoke(ChromeDevToolsServiceImpl.java:149)
	at com.github.kklisura.cdt.services.invocation.CommandInvocationHandler.invoke(CommandInvocationHandler.java:87)
	at com.sun.proxy.$Proxy28.captureScreenshot(Unknown Source)

**Comment by vania-pooh** [comment]
@Manikandan-18 I would take thread dump of frozed code first.
