### ISSUE TITLE
 Failed connecting to ws server {}

### ISSUE THREAD

**Issue by KritikaSahare1611** [aerokube/chrome-developer-tools-protocol-java-example#5]
io.github.sskorol.cdt.services.exceptions.WebSocketServiceException: Failed connecting to ws server {}
	at io.github.sskorol.cdt.services.impl.WebSocketServiceImpl.connect(WebSocketServiceImpl.java:114)
	at io.github.sskorol.cdt.services.impl.WebSocketServiceImpl.create(WebSocketServiceImpl.java:80)
	at io.github.sskorol.cdt.services.ChromeDevToolsService.from(ChromeDevToolsService.java:122)
	at com.healthkart.hkAutomation.browser.ChromeDevToolsHelper.traceNetworkCalls(ChromeDevToolsHelper.java:33)
	at com.healthkart.extentReportUtil.ExtentReportingBaseUtil.setup(ExtentReportingBaseUtil.java:420)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.MethodInvocationHelper$2.runConfigurationMethod(MethodInvocationHelper.java:421)
	at com.healthkart.extentReportUtil.ExtentReportingBaseUtil.run(ExtentReportingBaseUtil.java:741)
	at org.testng.internal.MethodInvocationHelper.invokeConfigurable(MethodInvocationHelper.java:435)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:382)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: jakarta.websocket.DeploymentException: Incorrect scheme in WebSocket endpoint URI=http://172.21.219.120:4444/devtools/ec1fc69c46011f052509fd3698c9f085/page
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:485)
	at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:355)
	at io.github.sskorol.cdt.services.impl.WebSocketServiceImpl.connect(WebSocketServiceImpl.java:92)
	... 33 more

I am using selenoid latest version docker pull aerokube/selenoid:latest
selenoid UI latest version  docker pull aerokube/selenoid-ui:latest 
and following maven dependency
<dependency>
			<groupId>io.github.sskorol</groupId>
			<artifactId>cdt-java-client</artifactId>
			<version>5.0.0</version>
		</dependency>

CHROME_DEVTOOLS_SELENOID_URL = "ws://172.21.219.120:4444/devtools/%s/page";

**Comment by vania-pooh** [comment]
It's saying you pass http:// instead of ws://.
```
URI=http://172.21.219.120:4444/devtools/ec1fc69c46011f052509fd3698c9f085/page
```

**Comment by andyherdwatch** [comment]
i have this problem too - Failed connecting to ws server {}
if (webDriver instanceof RemoteWebDriver) {
            RemoteWebDriver remoteDriver = (RemoteWebDriver) webDriver;
            devtools = ChromeDevToolsService.from(format("ws:" + REMOTE_BROWSER_SERVICE_URL.replace("http:", "")
                    + "/devtools/%s/page", remoteDriver.getSessionId()));
        }
I am using selenoid latest version docker pull aerokube/selenoid:latest
selenoid UI latest version docker pull aerokube/selenoid-ui:latest
and following maven dependency

io.github.sskorol
cdt-java-client
5.0.0

**Comment by andyherdwatch** [comment]
@KritikaSahare1611 do you fix this problem?

**Comment by KritikaSahare1611** [comment]
@andyherdwatch yes , my problem is fixed now

**Comment by andyherdwatch** [comment]
@KritikaSahare1611 what was the problem? maybe this solution will help me too

**Comment by KritikaSahare1611** [comment]
@andyherdwatch use this  
package com.healthkart.hkAutomation.browser;

import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;

import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.logging.LogType;
import org.openqa.selenium.logging.LoggingPreferences;
public class ChromeOptionsCapability {
	
	private ChromeOptionsCapability() {
	}
	
	private static ThreadLocal<String> dr = new ThreadLocal<>();
	
	
	public static String getMethodName() {
		return dr.get();
	}

	public static void setMethodName(String methodName) {
		dr.set(methodName);
	}

	public static void unload() {
		dr.remove();
	}
	
	
	public static ChromeOptions setChromeOptions()
	{
		return new ChromeOptions().addArguments("--disable-notifications")
	   .addArguments("disable-infobars").addArguments("start-maximized").addArguments("--remote-allow-origins=*");
	}
	
	public static ChromeOptions setChromeOptionsSelenoid()
	{
		HashMap<String, Object> chromePrefs = new HashMap<String, Object>();
		chromePrefs.put("intl.accept_languages", "hi");
		LoggingPreferences logPrefs = new LoggingPreferences();
		logPrefs.enable(LogType.BROWSER, Level.OFF);
		logPrefs.enable(LogType.PERFORMANCE, Level.ALL);
		ChromeOptions ops = new ChromeOptions();
		ops.addArguments("--disable-notifications")
		.addArguments("disable-infobars")
		.addArguments("start-maximized")
		.addArguments("--no-sandbox")
		.addArguments("--disable-setuid-sandbox")
		.addArguments("disable-dev-shm-usage")
		.addArguments("--remote-allow-origins=*");
		ops.setExperimentalOption("prefs", chromePrefs);
		ops.setCapability("goog:loggingPrefs", logPrefs);
		ops.setCapability("browserVersion", "latest");
		ops.setCapability("browserName", "chrome");

		Map<Object, Object> options = new HashMap<>();
		options.put("enableVNC", true);
		options.put("enableVideo", false);
		options.put("sessionTimeout", "10m");
		options.put("name", getMethodName());
		ops.setCapability("selenoid:options", options);
		return ops;
	}
}

**Comment by andyherdwatch** [comment]
thank you @KritikaSahare1611

**Comment by vania-pooh** [comment]
Let me close if issue seems to be resolved.
